### ISSUE TITLE
Omada OpenAPI

### ISSUE THREAD

**Issue by pduchnovsky** [dougbw/coredns_omada#28]
Hey, thanks for this :), really appreciate it, I no longer have to use local script :)

I have a question, any plans on implementing API V2 ?
So we could switch from using account to using client/secret pair ?

Also, I would appreciate if there was a way/option for this to only serve for PTR entries, without any upstream, would that be possible.

**Comment by dougbw** [comment]
Hi,

I will take a look at the V2 API and see what differences there are.

Regarding only serving PTR records only could you explain the use case for context?

You can remove the upstream entry from the Corefile - then the Omada plugin will only resolve the local addresses from the controller (devices, clients) so maybe that is close to what you are trying to achieve - it's not possible to only serve the PTR records as the zone is generated with both forward and PTR records in one go. It would be possible to add some config flags (e.g https://github.com/dougbw/coredns_omada/blob/main/config.go#L18) to control what records are added to the zone but I don't really see the benefit at the moment.

**Comment by pduchnovsky** [comment]
Apologies I meant to type rDNS (local addresses) instead of PTR :)

So removing the forward entry solves this for me, thanks :)

**Comment by dougbw** [comment]
FYI I have raised an issue for the open API support in the package which handles the omada API integration as that is where the bulk of the work would be initially (https://github.com/dougbw/go-omada/issues/9).

Other than some changes to authentication the API is quite similar, the endpoints look like they return less data than the existing API but still contain everything this project needs. 

I will keep this issue open in the mean time so that I don't forget about it.

**Comment by psybernoid** [comment]
I just came here to give the heads up that OpenAPI is being deprecated as of controller version 5.15. Then saw this open issue.

Details: https://community.tp-link.com/en/business/forum/topic/671250

**Comment by dougbw** [comment]
Thanks for letting me know. This project does not use the OpenAPI feature so will not be impacted if it is removed. The OpenAPI was only recently added and is separate to the built in API used by Omada web UI.
