### ISSUE TITLE
Clients not found by Omada

### ISSUE THREAD

**Issue by stordoff** [dougbw/coredns_omada#47]
This seems to be an Omada bug, but I'm wondering if there's a way to fix it/a workaround with coredns_omada. Fairly frequently, wired hosts disappear from the Omada client list (seemingly those with not much traffic). When this happens, coredns_omada can't resolve the client:

Expected:

```
>nslookup alpine-docker.int.stordoff.com 10.0.0.5
Server:  alpine-docker.int.stordoff.com
Address:  10.0.0.5

Name:    alpine-docker.int.stordoff.com
Address:  10.0.0.5
```

Actual:

```
>nslookup alpine-docker.int.stordoff.com 10.0.0.5
Server:  UnKnown
Address:  10.0.0.5

*** UnKnown can't find alpine-docker.int.stordoff.com: Server failed
```

alpine-docker is the host when the coredns_omada Docker image is running, and it has IP address 10.0.0.5 (static DHCP lease). Once the client reappears in the client list, it can be resolved again.

**Comment by dougbw** [comment]
Hey, this was something that crossed my mind as currently every time the refresh is run a new set of records is created, which can cause records to be removed quite aggressively (I also have a particular host which seems to flap in and out of the Omada controller).

It would be a straightforward change to start the refresh from the existing set of records, but  I would need to have a think about how to then cleanup stale records after a period of time, as keeping the records indefinitely could cause some incosistenties.

**Comment by stordoff** [comment]
Hi,

Thanks for replying. I don't know if it's possible or would cause other issues, but just keeping the DHCP reservations available indefinitely would resolve most of the issue for me. Any other hosts disappearing/reappearing are not a major concern (I assume I could add these reservations manually to coredns, but that defeats the purpose of keeping management within Omada).

**Comment by dougbw** [comment]
I could put the option to keep stale records behind an optional config property which would be quite a simple change. I will take a look the next time I am working on this.

**Comment by dougbw** [comment]
I have had a look at the code and am planning to make changes to support a couple of features.

First of all I will add resolution for DHCP reservations as managed by the Omada controller in the services page.

Secondly rather than starting from a fresh list of clients every refresh it will retain state across refresh intervals, whilst purging records once they exceed a configurable age (e.g 1 hour). This will make the refresh slightly less aggressive as I have had minor issues with records disappearing briefly if a client crashes/reboots/etc.

**Comment by dougbw** [comment]
I have just published a beta release with support for resolving DHCP reservations and persisting stale client/device records across refreshes. By default stale records are purged after 5 minutes (although this can be extended via config).

* https://github.com/dougbw/coredns_omada/releases/tag/v1.7.0-beta
* https://github.com/dougbw/coredns_omada/pkgs/container/coredns_omada/296621837?tag=1.7.0-beta

I am going to do some more testing before promoting this release, but initially it looks to be working fine.

**Comment by stordoff** [comment]
Thanks for that. I've pulled the beta Docker image (trying `stale_record_duration 60m` as a few of my clients disappear for extended periods) and it seems to be working fine for now. I'll let you know if I run into any issues.

**Comment by dougbw** [comment]
There was a bug regarding the stale_record_duration which should be fixed in the latest beta image - the records were being kept for much longer than the configured duration.

Also if you have clients which are static then creating a DHCP reservation would be more reliable. Now the DHCP reservations are supported these records will always be included in every refresh, so it does not rely on the client being active at all. If a client has no network activity for a period of time it seems to drop out of the Omada controller from my experience.

**Comment by stordoff** [comment]
> Also if you have clients which are static then creating a DHCP reservation would be more reliable.

Most of my main devices have DHCP reservations, which seem to work perfectly with the initial beta. I don't really need the other devices to have reliable DNS entries - they're mostly IoT/media devices - but it tidies up reporting in other tools, so it's nice to have (in hindsight, I think I ended up giving all the clients that disappear for longer periods DHCP reservations, so I can probably get rid of the `stale_record_duration 60m` option).

**Comment by dougbw** [comment]
The DHCP resolution and stale record caching has been release in https://github.com/dougbw/coredns_omada/releases/tag/v1.7.0 - closing issue
