### ISSUE TITLE
Error during make

### ISSUE THREAD

**Issue by Bobjan-Joumoer** [dougbw/coredns_omada#9]
/coredns$ sudo make
go generate coredns.go
# command-line-arguments
./directives_generate.go:103:11: undefined: os.WriteFile
note: module requires Go 1.20
coredns.go:3: running "go": exit status 2
make: *** [Makefile:22: core/plugin/zplugin.go] Error 1

**Comment by dougbw** [comment]
Hi, 

This looks like you are getting an error running `make` on the coredns repo and the error looks go version related.

* I suspect you need to update your go version (to 1.20)? `go version` to check what is installed
* If you have made changes to the `plugin.cfg` / `go.mod` files then try and reset the `coredns` repo and see if you still get the error, if it persists then you would be better posting the issue on the main `coredns` repo rather than here

Many thanks,
Doug
